[package]
name = "tsh"
description="A simple command line tool to move files to trash"
repository = "https://github.com/imnyang/tsh"

authors = ["imnyang <me@imnya.ng>"]
license = "GPL-3.0"
version = "1.1.0"
edition = "2024"

[dependencies]
trash = "5"
